name: CI
env:
  TZ: Asia/Shanghai

on:
  push:
    paths-ignore:
      - '/readme/*'
      - '**/README.md'
      - '**/ChangeLog.txt'
      - '.github/workflows/*'
      - '!.github/workflows/main.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: init custom env
        run: |
          set -a
          BUILD_NAME="${GITHUB_REPOSITORY#*/}"
          if [[ ${GITHUB_REF} == refs/tags* ]]
          then
              BUILD_VERSION=${GITHUB_REF#refs/tags/}
          elif [[ ${GITHUB_REF} == refs/pull* ]]
          then
              num=${GITHUB_REF#refs/pull/}
              num=${num%/merge}
              BUILD_VERSION=pr-${num}-"$(date +'%Y%m%d%H%M%S')"
          else
              BUILD_VERSION="$(date +'%Y%m%d%H%M%S')"
          fi
          BUILD_NAME_WITH_VERSION="$BUILD_NAME-$BUILD_VERSION"
          echo BUILD_NAME="$BUILD_NAME" >> .custom_env
          echo BUILD_VERSION="$BUILD_VERSION" >> .custom_env
          echo BUILD_NAME_WITH_VERSION="$BUILD_NAME_WITH_VERSION" >> .custom_env
          cat .custom_env >> $GITHUB_ENV

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Build with Gradle
        run: |
          ./gradlew :hook:assembleRelease

      - name: Upload APK for download
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: ./hook/build/outputs/apk/release/*.apk
